- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Create config dir
  file:
    path: /etc/containerd
    state: directory

- name: Generate default config
  command: containerd config default
  register: containerd_config

- name: Save config to file
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml

- name: Enable SystemdCgroup for containerd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup ='
    line: '        SystemdCgroup = true'

- name: Restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes
  when: not ansible_check_mode